# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres-ppal1: 
    container_name: postgres-ppal1
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
